// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


/*! 
 * @file MagneticField.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */
#ifndef _SENSOR_MSGS_MAGNETIC_FIELD_HPP_
#define _SENSOR_MSGS_MAGNETIC_FIELD_HPP_


#include "micrortps.hpp"
#include <topic_config.h>
#include <topic.hpp>


#include "std_msgs/Header.hpp"
#include "geometry_msgs/Vector3.hpp"

namespace sensor_msgs {


class MagneticField : public ros2::Topic<MagneticField>
{
public: 
    std_msgs::Header header;
    geometry_msgs::Vector3 magnetic_field;
    double magnetic_field_covariance[9];

  MagneticField():
    Topic("sensor_msgs::msg::dds_::MagneticField_", SENSOR_MSGS_MAGNETIC_FIELD_TOPIC),
    header(), magnetic_field()
  { 
    memset(magnetic_field_covariance, 0, sizeof(magnetic_field_covariance));
  }

  virtual bool serialize(MicroBuffer* writer, const MagneticField* topic)
  {
    header.serialize(writer, &topic->header);
    magnetic_field.serialize(writer, &topic->magnetic_field);
    serialize_array_double(writer, topic->magnetic_field_covariance, 9);

    return writer->error == BUFFER_OK;
  }

  virtual bool deserialize(MicroBuffer* reader, MagneticField* topic)
  {
    header.deserialize(reader, &topic->header);
    magnetic_field.deserialize(reader, &topic->magnetic_field);
    deserialize_array_double(reader, topic->magnetic_field_covariance, 9);

    return reader->error == BUFFER_OK;
  }

  virtual uint32_t size_of_topic(const MagneticField* topic)
  {
    uint32_t size = 0;

    size += header.size_of_topic(&topic->header);
    size += magnetic_field.size_of_topic(&topic->magnetic_field);
    size += ((9) * 8) + get_alignment(size, 8);

    return size;
  }

};

} // namespace sensor_msgs


#endif // _SENSOR_MSGS_MAGNETIC_FIELD_HPP_
